on: [push]
jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - run: echo "A" > note.txt
      - run: cat note.txt
  two:
    needs: one
    runs-on: ubuntu-latest
    steps:
      - run: cat note.txt
